### PR TITLE
Support only messages

### LINKED ISSUE #54: message only packages are failing to generate documentation
A job like Rdoc_common_interfaces https://build.ros2.org/view/Rdoc/job/Rdoc__common_interfaces__ubuntu_jammy_amd64/

It is building sensor_msgs because they have an include folder and so doxygen is triggered. But all the other packages in that repository generate no content.

Example: https://build.ros2.org/view/Rdoc/job/Rdoc__common_interfaces__ubuntu_jammy_amd64/26/console

### PR DESCRIPTION
**Pull request by rkent**
This was less complex than I feared. Test case ```only_messages``` shows how this works.

I find the whole process of deciding what to run to be hard to understand. Here I change the decision to run breathe based on the existence of the doxygen output, while previously it was done based on build type. Both seem a little too much like black magic to me. I feel like it could use a refactoring, but maybe the complexity is just inherent and hard to improve.

Fixes #54

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
Using the logic to run breathe if doxygen was run makes sense. It's specifically for integrating the doxygen content into a sphinx runner. The previous logic was a proxy for where we were expecting doxygen to be run. (Aka c++ build types) But directly detecting that there's content available makes sense and is likely more robust.

I've tested that this is working for packages known to be previously failing.

**Comment by tfoote** [comment]
Confirmed building on the bulidfarm with message only packages: https://docs.ros.org/en/rolling/p/trajectory_msgs/

**Comment by Yadunund** [comment]
🎉 🎉 🎉

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/rosdoc2-undergoing-significant-change/36905/2

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/plans-for-ros-2-documentation-particularly-api-docs/28638/23

**Pull request merged**
